version: "3.1"
services:
  client:
    container_name: mediapipe_learn_docs
    image: nginx:1.22.1
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs:/usr/share/nginx/html